backend:
  name: git-gateway

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Accueil"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {
              label: Mainpitch, 
              name: mainpitch, 
              widget: object, 
              fields: [
                {label: Title, name: title, widget: string},
                {label: Description, name: description, widget: text},
                {label: Image, name: image, widget: image},
              ]
          }
          - {
            label: Intro,
            name: intro,
            widget: object,
            fields: [
              {label: Heading, name: heading, widget: string},
              {label: Description, name: description, widget: string},
              {label: Icones, name: blurbs, widget: list, fields: [
                {label: Image, name: image, widget: image},
                {label: Text, name: text, widget: text},
              ]}
            ]
          }
          - {
            label: Presentations,
            name: presentations,
            widget: list,
            fields: [
              {label: Photo, name: photo, widget: image},
              {label: Titre, name: titre, widget: string},
              {label: Description, name: description, widget: text},
            ]
          }
          - {
            label: Decouvrir,
            name: decouvrir,
            widget: object,
            fields: [
              {label: Title, name: title, widget: string},
              {label: Lien, name: lien, widget: string},
              {label: Image, name: image, widget: image},
            ]
          }
      - file: "src/pages/mediation.md"
        label: "Médiation animale"
        name: "mediation"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "mediation-page"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Titre page", name: "titrePage", widget: string}
          - {label: "Image", name: "imageIntro", widget: image}
          - {label: "Titre cartes", name: "titreCartes", widget: string}
          - {
            label: Cartes,
            name: cartes,
            widget: list,
            fields: [
              {label: Image, name: image, widget: image},
              {label: Texte, name: texte, widget: string},
              {label: Lien, name: lien, widget: string},
            ]
          }
          - {
            label: Citation,
            name: citation,
            widget: object,
            fields: [
              {label: Texte, name: texte, widget: text},
              {label: "Auteur / Autrice", name: auteur, widget: string}
            ]
          }
      - file: "src/pages/mediation/collegues.md"
        label: "Collègues"
        name: "collegues"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "collegues-page"}
          - {label: "Titre page", name: "titrePage", widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
          - {
            label: Presentations,
            name: presentations,
            widget: list,
            fields: [
              {label: Photo, name: photo, widget: image},
              {label: Titre, name: titre, widget: string},
              {label: Description, name: description, widget: text},
            ]
          }
          - {
            label: Icones,
            name: blurbs,
            widget: list,
            fields: [
              {label: Image, name: image, widget: image},
              {label: Text, name: text, widget: text},
            ]
          }
      - file: "src/pages/mediation/prestations.md"
        label: "Prestations MA"
        name: "prestations-ma-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "prestations-ma-page"}
      - file: "src/pages/comportement.md"
        label: "Comportement canin"
        name: "comportement"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "comportement-page"}
      - file: "src/pages/activites.md"
        label: "Activités et sports canins"
        name: "activites"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "activites-page"}
          - {label: "Image", name: "imageIntro", widget: image}
          - {label: "Titre page", name: "titrePage", widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Titre cartes", name: "titreCartes", widget: string}
          - {
            label: Cartes,
            name: cartes,
            widget: list,
            fields: [
              {label: Image, name: image, widget: image},
              {label: Texte, name: texte, widget: string},
              {label: Lien, name: lien, widget: string},
            ]
          }
      - file: "src/pages/activites/oberythmee.md"
        label: "Obérythmée"
        name: "oberythmee"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "oberythmee-page"}
          - {label: "Image", name: "imageIntro", widget: image}
          - {label: "Survol image", name: "survolImageIntro", widget: string}
          - {label: "Titre page", name: "titrePage", widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
          - {
            label: "Pré-requis",
            name: "prerequis",
            widget: list,
            fields: [
              {label: Texte, name: texte, widget: string},
            ]
          }
          - {
            label: "Tarifs",
            name: "tarifs",
            widget: list,
            fields: [
              {label: Titre, name: titre, widget: string},
              {label: Sous titre, name: sousTitre, widget: string},
              {
                label: "Tarifs",
                name: "tarifs",
                widget: list,
                fields: [
                  {label: Texte, name: texte, widget: string},
                ]
              }
            ]
          }
          - {label: "Sous texte tarifs", name: "sousTexteTarifs", widget: string}
          - {
            label: "Images bas de page",
            name: "imagesBasDePage",
            widget: list,
            fields: [
              {label: Image, name: image, widget: image},
              {label: "Survol image", name: "survolImage", widget: string},
            ]
          }
          - {
            label: "Liens crédits photo",
            name: "liensCreditPhoto",
            widget: list,
            fields: [
              {label: "Texte", name: "texte", widget: string},
              {label: "Lien", name: "lien", widget: string},
            ]
          }
      - file: "src/pages/activites/agility.md"
        label: "Agility"
        name: "agility"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "agility-page"}
          - {label: "Image", name: "imageIntro", widget: image}
          - {label: "Survol image", name: "survolImageIntro", widget: string}
          - {label: "Titre page", name: "titrePage", widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
          - {
            label: "Pré-requis",
            name: "prerequis",
            widget: list,
            fields: [
              {label: Texte, name: texte, widget: string},
            ]
          }
          - {
            label: "Tarifs",
            name: "tarifs",
            widget: list,
            fields: [
              {label: Titre, name: titre, widget: string},
              {label: Sous titre, name: sousTitre, widget: string},
              {
                label: "Tarifs",
                name: "tarifs",
                widget: list,
                fields: [
                  {label: Texte, name: texte, widget: string},
                ]
              }
            ]
          }
          - {label: "Sous texte tarifs", name: "sousTexteTarifs", widget: string}
          - {
            label: "Images bas de page",
            name: "imagesBasDePage",
            widget: list,
            fields: [
              {label: Image, name: image, widget: image},
              {label: "Survol image", name: "survolImage", widget: string},
            ]
          }
          - {
            label: "Liens crédits photo",
            name: "liensCreditPhoto",
            widget: list,
            fields: [
              {label: "Texte", name: "texte", widget: string},
              {label: "Lien", name: "lien", widget: string},
            ]
          }
      - file: "src/pages/activites/medical-training.md"
        label: "Medical training"
        name: "medical-training"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "medical-training-page"}
          - {label: "Image", name: "imageIntro", widget: image}
          - {label: "Survol image", name: "survolImageIntro", widget: string}
          - {label: "Titre page", name: "titrePage", widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
          - {
            label: "Pré-requis",
            name: "prerequis",
            widget: list,
            fields: [
              {label: Texte, name: texte, widget: string},
            ]
          }
          - {
            label: "Tarifs",
            name: "tarifs",
            widget: list,
            fields: [
              {label: Titre, name: titre, widget: string},
              {label: Sous titre, name: sousTitre, widget: string},
              {
                label: "Tarifs",
                name: "tarifs",
                widget: list,
                fields: [
                  {label: Texte, name: texte, widget: string},
                ]
              }
            ]
          }
          - {label: "Sous texte tarifs", name: "sousTexteTarifs", widget: string}
          - {
            label: "Images bas de page",
            name: "imagesBasDePage",
            widget: list,
            fields: [
              {label: Image, name: image, widget: image},
              {label: "Survol image", name: "survolImage", widget: string},
            ]
          }
          - {
            label: "Liens crédits photo",
            name: "liensCreditPhoto",
            widget: list,
            fields: [
              {label: "Texte", name: "texte", widget: string},
              {label: "Lien", name: "lien", widget: string},
            ]
          }
      - file: "src/pages/activites/shaping.md"
        label: "Shaping"
        name: "shaping"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "shaping-page"}
          - {label: "Image", name: "imageIntro", widget: image}
          - {label: "Survol image", name: "survolImageIntro", widget: string}
          - {label: "Titre page", name: "titrePage", widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
          - {
            label: "Pré-requis",
            name: "prerequis",
            widget: list,
            fields: [
              {label: Texte, name: texte, widget: string},
            ]
          }
          - {
            label: "Tarifs",
            name: "tarifs",
            widget: list,
            fields: [
              {label: Titre, name: titre, widget: string},
              {label: Sous titre, name: sousTitre, widget: string},
              {
                label: "Tarifs",
                name: "tarifs",
                widget: list,
                fields: [
                  {label: Texte, name: texte, widget: string},
                ]
              }
            ]
          }
          - {label: "Sous texte tarifs", name: "sousTexteTarifs", widget: string}
          - {
            label: "Images bas de page",
            name: "imagesBasDePage",
            widget: list,
            fields: [
              {label: Image, name: image, widget: image},
              {label: "Survol image", name: "survolImage", widget: string},
            ]
          }
          - {
            label: "Liens crédits photo",
            name: "liensCreditPhoto",
            widget: list,
            fields: [
              {label: "Texte", name: "texte", widget: string},
              {label: "Lien", name: "lien", widget: string},
            ]
          }
      - file: "src/pages/a-propos.md"
        label: "A propos"
        name: "a-propos"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "a-propos-page"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Image", name: "imageIntro", widget: image}
          - {
              label: Presentation, 
              name: presentation, 
              widget: object, 
              fields: [
                {label: Image, name: image, widget: image},
                {label: Description, name: description, widget: text},
              ]
          }
          - {label: "Diplômes / Certificats", name: "diplomesCertificats", widget: list, fields: [
              {label: "Année", name: "annee", widget: string},
              {label: "Description", name: "description", widget: text},
              {label: "Organisme", name: "organisme", widget: text},
            ]}
          - {label: "Formations / Stages", name: "formationsStages", widget: list, fields: [
              {label: "Année", name: "annee", widget: string},
              {label: "Description", name: "description", widget: text},
              {label: "Organisme", name: "organisme", widget: text},
            ]}
          - {label: "Expériences", name: "experiences", widget: list, fields: [
              {label: "Année", name: "annee", widget: string},
              {label: "Description", name: "description", widget: text},
              {label: "Organisme", name: "organisme", widget: text},
            ]}
      - file: "src/pages/cgv.md"
        label: "CGV"
        name: "cgv"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "cgv-page"}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "prestations-ma-collection"
    label: "Prestations MA"
    folder: "/src/pages/mediation/prestations"
    create: true
    slug: "{{titre}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "prestation-ma"}
      - {label: "Ordre", name: "ordre", widget: "number", default: 1, value_type: "int", step: 1}
      - {label: "Titre", name: "titre", widget: "string"}
      - {label: "Image", name: image, widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Prix", name: "prix", widget: "string"}