backend:
  name: git-gateway
  branch: develop

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Accueil"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {
            label: Services,
            name: services,
            widget: list,
            fields: [
              {label: Photo, name: photo, widget: image},
              {label: Titre, name: titre, widget: string},
              {label: Description, name: description, widget: markdown},
              {label: Lien, name: lien, widget: string, required: false, default: ''},
              {label: Titre du lien, name: titreLien, widget: string, required: false, default: ''},
            ]
          }
          - {
            label: Certifications,
            name: certifications,
            widget: list,
            fields: [
              {label: Image, name: image, widget: image},
              {label: Lien, name: lien, widget: string, required: false, default: ''},
            ]
          }
      - file: "src/pages/a-propos.md"
        label: "A propos"
        name: "a-propos"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "a-propos-page"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Image", name: "imageIntro", widget: image}
          - {
              label: Presentation, 
              name: presentation, 
              widget: object, 
              fields: [
                {label: Image, name: image, widget: image},
                {label: Description, name: description, widget: text},
              ]
          }
          - {label: "Diplômes / Certificats", name: "diplomesCertificats", widget: list, fields: [
              {label: "Année", name: "annee", widget: string},
              {label: "Description", name: "description", widget: text},
              {label: "Organisme", name: "organisme", widget: text},
            ]}
          - {label: "Formations / Stages", name: "formationsStages", widget: list, fields: [
              {label: "Année", name: "annee", widget: string},
              {label: "Description", name: "description", widget: text},
              {label: "Organisme", name: "organisme", widget: text},
            ]}
          - {label: "Expériences", name: "experiences", widget: list, fields: [
              {label: "Année", name: "annee", widget: string},
              {label: "Description", name: "description", widget: text},
              {label: "Organisme", name: "organisme", widget: text},
            ]}
      - file: "src/pages/cgv.md"
        label: "CGV"
        name: "cgv"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "cgv-page"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/zi-frais-deplacement.md"
        label: "Zone d'intervention et frais de déplacement"
        name: "zi-frais-deplacement"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "zi-frais-deplacement-page"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/articles.md"
        label: "Articles"
        name: "articles-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "articles-page"}
  - name: "articles-collection"
    label: "Articles"
    folder: "src/pages/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Auteur(e)", name: "auteur", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Mettre en avant", name: "featuredpost", widget: "boolean", default: false, required: false}
      - {label: "Image de l'aperçu", name: "featuredimage", widget: image}
      - {label: "Article", name: "body", widget: "markdown"}
      - {label: "Mots clés", name: "tags", widget: "list"}
  - name: "services-collection"
    label: "Services"
    folder: "src/pages/services"
    create: true
    slug: "{{lienService}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "service"}
      - {label: "Lien service", name: "lienService", widget: "string"}
      - {label: "Photo haut de page", name: "photoHaut", widget: image}
      - {label: "Nom du service", name: "nomService", widget: "string"}
      - {label: "Description du service", name: "body", widget: "markdown"}
      - {
          label: "Lien complémentaire",
          name: "lienComplementaire",
          widget: "string",
          required: false,
          default: '',
        }
      - {
          label: "Titre du lien",
          name: "titreLienComplementaire",
          widget: "string",
          required: false,
          default: '',
        }
      - {
          label: "Tarifs service",
          name: "tarifsService",
          widget: list,
          fields: [
            {label: Titre, name: titre, widget: string},
            {label: Sous-titre, name: sousTitre, widget: string},
            {label: Image, name: image, widget: image},
            {label: Durée/Prix, name: dureePrix, widget: string},
            {label: Description, name: description, widget: markdown},
          ]
        }
      - {
          label: "Images bas de page",
          name: "imagesBasDePage",
          widget: list,
          fields: [
            {label: Image, name: image, widget: image},
            {label: "Survol image", name: "survolImage", widget: string},
          ]
        }
