backend:
  name: git-gateway

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Accueil"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {
              label: Mainpitch, 
              name: mainpitch, 
              widget: object, 
              fields: [
                {label: Title, name: title, widget: string},
                {label: Description, name: description, widget: text},
                {label: Image, name: image, widget: image},
              ]
          }
          - {
            label: Intro,
            name: intro,
            widget: object,
            fields: [
              {label: Heading, name: heading, widget: string},
              {label: Description, name: description, widget: string},
              {label: Blurbs, name: blurbs, widget: list, fields: [
                {label: Image, name: image, widget: image},
                {label: Text, name: text, widget: text},
              ]}
            ]
          }
          - {
            label: Presentations,
            name: presentations,
            widget: list,
            fields: [
              {label: Photo, name: photo, widget: image},
              {label: Titre, name: titre, widget: string},
              {label: Description, name: description, widget: text},
            ]
          }
          - {
            label: Decouvrir,
            name: decouvrir,
            widget: object,
            fields: [
              {label: Title, name: title, widget: string},
              {label: Lien, name: lien, widget: string},
              {label: Image, name: image, widget: image},
            ]
          }
      - file: "src/pages/mediation.md"
        label: "Médiation animale"
        name: "mediation"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "mediation-page"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Titre page", name: "titrePage", widget: string}
          - {label: "Image", name: "imageIntro", widget: image}
          - {label: "Titre cartes", name: "titreCartes", widget: string}
          - {
            label: Cartes,
            name: cartes,
            widget: list,
            fields: [
              {label: Image, name: image, widget: image},
              {label: Texte, name: texte, widget: string},
              {label: Lien, name: lien, widget: string},
            ]
          }
      - file: "src/pages/comportement.md"
        label: "Comportement canin"
        name: "comportement"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "activites-page"}
      - file: "src/pages/activites.md"
        label: "Activités et sports canins"
        name: "activites"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "comportement-page"}
      - file: "src/pages/a-propos.md"
        label: "A propos"
        name: "a-propos"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "a-propos-page"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Image", name: "imageIntro", widget: image}
          - {
              label: Presentation, 
              name: presentation, 
              widget: object, 
              fields: [
                {label: Image, name: image, widget: image},
                {label: Description, name: description, widget: text},
              ]
          }
          - {label: "Diplômes / Certificats", name: "diplomesCertificats", widget: list, fields: [
              {label: "Année", name: "annee", widget: string},
              {label: "Description", name: "description", widget: text},
              {label: "Organisme", name: "organisme", widget: text},
            ]}
          - {label: "Formations / Stages", name: "formationsStages", widget: list, fields: [
              {label: "Année", name: "annee", widget: string},
              {label: "Description", name: "description", widget: text},
              {label: "Organisme", name: "organisme", widget: text},
            ]}
          - {label: "Expériences", name: "experiences", widget: list, fields: [
              {label: "Année", name: "annee", widget: string},
              {label: "Description", name: "description", widget: text},
              {label: "Organisme", name: "organisme", widget: text},
            ]}

